In [51]:
import numpy as np
x_train = [[3.3,2.3],  #样本数据
           [3.1,1.7],
           [1.3,3.3],
           [3.5,4.6],
           [2.2,2.8],
           [7.4,4.6],
           [5.7,3.5],
           [9.1,2.5],
           [7.7,3.4],
           [7.9,0.7]]
y_train=[0,0,0,0,0,1,1,1,1,1] #标签数据

In [59]:
x = np.array([1,3.5]) #预测数据

In [53]:
from sklearn.neighbors import KNeighborsClassifier #导入K近邻算法模型
knn_clf = KNeighborsClassifier()
knn_clf

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

### 参数说明
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

algorithm:{'auto','ball_tree','kd_tree','brute'}计算最近邻的方法，可根据需要自己选择。
leaf_size: int，默认30，leaf size passed to BallTree or KDTree
metric: str or DistanceMetric,默认'minKowski',使用距离矩阵，为了树。P值参考。
metric_params：dict,默认None，添加键的分配为矩阵函数。
n_jobs：工作使用内核。
n_neighbors：int，默认5，默认邻居数量。
P:int，默认2，P=1使用曼哈顿距离，P=2使用欧氏距离。
weights：确定近邻的权重，'uniform'权重一样，'distance'指权重为距离的倒数，默认'uniform'，也可以自己定义函数确定权重的方式。



欧拉距离、曼哈顿距离、明可夫斯基距离
https://blog.csdn.net/dddxxxx/article/details/110455492

其他距离：
向量空间余弦相似度
调整余弦相似度
皮尔森相关系数
Jaccard相似系数

In [54]:
knn_clf = KNeighborsClassifier(n_neighbors=6) #创建算法模型
knn_clf.fit(x_train,y_train)  #拟合或者称为训练
# knn_clf.predict(x)
knn_clf

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [55]:
x

array([8. , 3.3])

In [60]:
x_predict = x.reshape(1,-1) #把预测的数据从一维变成二维矩阵
x_predict

array([[1. , 3.5]])

In [61]:
y_predict = knn_clf.predict(x_predict) #输出预测数据结果

In [62]:
y_predict

array([0])

In [67]:
from sklearn import datasets
iris = datasets.load_iris()
#print(iris.DESCR)
data = iris.data
target = iris.target
target_names = iris.target_names
target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')