In [279]:
# https://blog.csdn.net/weixin_60737527/article/details/124141293
import numpy as np

In [280]:
np.random.seed(50) #赋予随机数一个种子，固定随机数
x = np.random.normal(0,1,size=(2000,2))  #使用随机数生成符合正态分布

In [281]:
x

array([[-1.56035211, -0.0309776 ],
       [-0.62092842, -1.46458049],
       [ 1.41194612, -0.47673214],
       ...,
       [-2.56273701, -1.04709943],
       [-0.31619173,  1.89357786],
       [-0.17203994, -0.25321262]])

In [282]:
x[:,0]
x[:,1]

array([-0.0309776 , -1.46458049, -0.47673214, ..., -1.04709943,
        1.89357786, -0.25321262])

In [283]:
(x[:,0]**2+x[:,1])

array([ 2.4037211 , -1.07902838,  1.51685971, ...,  5.52052156,
        1.99355507, -0.22361488])

In [284]:
y = np.array((x[:,0]**2+x[:,1]) <1.5,dtype='int') #构造分类 逻辑回归分类，第一列点乘2+第二列总和 <1.5 为分类条件

In [285]:
y

array([0, 1, 0, ..., 0, 0, 1])

In [286]:
#加入噪音,为了更接近真实数据
for _ in range(20): #  _表示占位，不使用其值
    y[np.random.randint(2000)] = 1
y

array([0, 1, 0, ..., 0, 0, 1])

In [287]:
from sklearn.linear_model import LogisticRegression #线性回归
from sklearn.model_selection import train_test_split #划分数据集

In [288]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=666)

In [289]:
x_train.shape

(1600, 2)

In [290]:
x_test.shape

(400, 2)

In [291]:
log_reg = LogisticRegression() #创建算法
log_reg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [292]:
#训练数据的准确率得分
log_reg.score(x_train,y_train)

0.78375

In [293]:
#测试数据的准确率得分
log_reg.score(x_test,y_test)

0.81

In [294]:
from sklearn.metrics import accuracy_score ##准确率得分
from sklearn.metrics import precision_score,recall_score ##精准率，召回率得分

In [295]:
y_predict = log_reg.predict(x_test)
y_predict

array([0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,

In [296]:
y_test

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,

In [297]:
accuracy_score(y_test,y_predict)

0.81

In [298]:
precision_score(y_test,y_predict)

0.8080495356037152

In [299]:
recall_score(y_test,y_predict)

0.9490909090909091

In [300]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_predict)

array([[ 63,  62],
       [ 14, 261]], dtype=int64)

In [301]:
print("准确率：(TN+TP)/(TN+FP+FN+TP)",(63+261)/(63+62+14+261))
print("精准率：TP/(FP+TP)",261/(62+261))
print("召回率：TP/(FN+TP)",261/(14+261))

准确率：(TN+TP)/(TN+FP+FN+TP) 0.81
精准率：TP/(FP+TP) 0.8080495356037152
召回率：TP/(FN+TP) 0.9490909090909091
