In [26]:
"""
注释
"""

'\n注释\n'

In [27]:
a=10
b=20
c=a+b
c

30

## markdown

In [28]:
import numpy as np # 导入numpy的第三方库
a = [10,True,'12312']
arr = np.array([1,2,3,4,1,11,231,42])
arr




array([  1,   2,   3,   4,   1,  11, 231,  42])

In [33]:
ones4 = np.ones(4)
ones4


array([1., 1., 1., 1.])

In [35]:
zero10 = np.zeros(10)
zero10

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
a = np.zeros((4,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [36]:
np.full(5,2)

array([2, 2, 2, 2, 2])

In [39]:
np.random.random(5)

array([0.61125754, 0.56080251, 0.57198839, 0.56086434, 0.94417715])

In [40]:
## 二维
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
np.random.random((3,3))

array([[0.58072243, 0.40905561, 0.31524666],
       [0.0204142 , 0.81324879, 0.9760922 ],
       [0.81354567, 0.83234323, 0.19752651]])

In [42]:
## 三位
np.random.random((3,3,3))

array([[[0.46667529, 0.45011644, 0.70981895],
        [0.69433147, 0.09597278, 0.67915939],
        [0.98944304, 0.71264404, 0.22805426]],

       [[0.9421567 , 0.31479456, 0.46783017],
        [0.4546833 , 0.79854178, 0.45726782],
        [0.45955758, 0.53588305, 0.6170551 ]],

       [[0.67137411, 0.37784075, 0.83092131],
        [0.15526206, 0.49199467, 0.17902703],
        [0.47641602, 0.828403  , 0.5200857 ]]])

In [43]:
data = np.array([1,2,3,12,31,23124,0,0,1122,54])
3*data

array([    3,     6,     9,    36,    93, 69372,     0,     0,  3366,
         162])

In [50]:
data2 = np.array([[1,2,3]])
data3 = np.array([[3,2,1],[3,2,1]])
data2*data3

array([[3, 4, 3],
       [3, 4, 3]])