In [27]:
import numpy as np

In [28]:
arr1 = np.array([1,2,3])
arr2 = np.array([10,20,30])
arr1 + arr2

array([11, 22, 33])

In [29]:
np.dot(arr1,arr2) # 对应位置相乘再相加

140

In [30]:
arr3 = np.array([[1,1,1],
                [2,2,2],
                [3,3,3]])
arr4 = np.array([[10,10,10],[20,20,20],[30,30,30]])
arr3.dot(arr4)

array([[ 60,  60,  60],
       [120, 120, 120],
       [180, 180, 180]])

### 两个矩阵做点乘满足条件：左边矩阵的行数等于右边矩阵的列。结果矩阵是：左边的行数，右边的列数

In [31]:
arr3 = np.array([[1,1,1],
                [2,2,2]])  # 2x3 两行三列
arr4 = np.array([[10,10],[20,20],[30,30]])  # 3x2 三行两列
# arr3.dot(arr4) #矩阵形状不同，左边行列=右边列行，左边列行=右边行列   2x2列
arr4.dot(arr3) #3x3列

array([[30, 30, 30],
       [60, 60, 60],
       [90, 90, 90]])

In [32]:
arr4.shape

(3, 2)

In [33]:
arr3.ndim

2

In [34]:
arr3.size

6

In [35]:
arr3.T

array([[1, 2],
       [1, 2],
       [1, 2]])

In [36]:
#reshape转变形状
arr3.reshape(1,6)

array([[1, 1, 1, 2, 2, 2]])

In [37]:
arr3.reshape(6,1)

array([[1],
       [1],
       [1],
       [2],
       [2],
       [2]])

In [38]:
arr5 = np.arange(10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])